global_costmap:
  update_frequency: 1.0
  static_map: false  # Disable static map
  rolling_window: false
  width: 400
  height: 400
  origin_x: -200
  origin_y: -200
  resolution: 0.25
  publish_voxel_map: false

  inflation_layer:
    inflation_radius: 3.5
    cost_scaling_factor: 2 # Lower values prefer global plans that are further away from obstacles