TebLocalPlannerROS:
    odom_topic: odom
    map_frame: world

    max_vel_x: 3.0
    max_vel_x_backwards: 0.5
    max_vel_theta: 2.0
    acc_lim_x: 4.0
    acc_lim_theta: 4.0

    min_in_place_vel_theta: 0.1

    min_turning_radius: 3.0
    wheelbase: 2.63

    # Two circle model is supposed to be faster
    footprint_model:
        type: "two_circles"
        front_offset: 1.25 # for type "two_circles"
        front_radius: 1.0 # for type "two_circles"
        rear_offset: 1.25 # for type "two_circles"
        rear_radius: 1.0 # for type "two_circles"
        vertices: [[-3.25, -0.8], [-3.25, 0.8], [0.75, 0.8], [0.75, -0.8]]

    # Stopped velocity thresholds
    trans_stopped_vel: 0.05
    theta_stopped_vel: 0.05

    # Goal tolerances
    xy_goal_tolerance: 0.3
    yaw_goal_tolerance: 0.2

    # Trajectory simulation parameters
    teb_autosize: true
    dt_ref: 0.05
    dt_hysteresis: 0.01
    max_global_plan_lookahead_dist: 20.0
    feasibility_check_no_poses: 5
    global_plan_overwrite_orientation: true
    allow_init_with_backwards_motion: false
    max_samples: 6

    occdist_scale: 0.8
    forward_point_distance: 0.1

    # Oscillation prevention
    oscillation_recovery: true
    oscillation_v_eps: 0.1
    oscillation_omega_eps: 0.1
    oscillation_recovery_steps: 4
    stop_time_buffer: 0.2
    oscillation_reset_dist: 0.3

    # Optimization parameters
    no_inner_iterations: 8
    no_outer_iterations: 4

    min_obstacle_dist: 1.5
    inflation_dist: 1.8

    enable_multithreading: true
    max_number_classes: 1

    global_plan_viapoint_sep: 0.25
    via_points_ordered: true
